import * as crypto from "crypto";
import { connectPrisma, getPrismaClient } from "./client";
import type { PrismaClient } from "../generated";

/**
 * Programmatic create/reset of the SQLite schema (ITD-90).
 *
 * The test harness calls resetDatabase() from a before() hook — no shelling
 * out to the Prisma CLI. DDL is embedded below so the runtime path never
 * reads a file (QA S3). The DDL is generated from prisma/schema.prisma;
 * regenerate it with `npm run db:sync-ddl` whenever the schema changes.
 *
 * Generated by:
 *   prisma migrate diff --from-empty --to-schema prisma/schema.prisma --script
 * (prisma 7.10.0)
 */

/** Tables in dependency-safe drop order (SQLite has no FKs here; cosmetic). */
export const TABLES: string[] = [
  "medici_id_sequence",
  "medici_balances",
  "medici_locks",
  "medici_journals",
  "medici_transactions",
];

export const DDL = `-- CreateTable
CREATE TABLE "medici_transactions" (
    "_id" TEXT NOT NULL PRIMARY KEY,
    "credit" REAL NOT NULL,
    "debit" REAL NOT NULL,
    "meta" TEXT,
    "datetime" DATETIME NOT NULL,
    "account_path" TEXT NOT NULL,
    "accounts" TEXT NOT NULL,
    "book" TEXT NOT NULL,
    "memo" TEXT NOT NULL,
    "_journal" TEXT NOT NULL,
    "timestamp" DATETIME NOT NULL,
    "voided" BOOLEAN,
    "void_reason" TEXT,
    "_original_journal" TEXT,
    "account_path_0" TEXT,
    "account_path_1" TEXT,
    "account_path_2" TEXT
);

-- CreateTable
CREATE TABLE "medici_journals" (
    "_id" TEXT NOT NULL PRIMARY KEY,
    "datetime" DATETIME NOT NULL,
    "memo" TEXT NOT NULL DEFAULT '',
    "_transactions" TEXT NOT NULL DEFAULT '[]',
    "book" TEXT NOT NULL,
    "voided" BOOLEAN,
    "void_reason" TEXT
);

-- CreateTable
CREATE TABLE "medici_locks" (
    "_id" TEXT NOT NULL PRIMARY KEY,
    "book" TEXT NOT NULL,
    "account" TEXT NOT NULL,
    "updatedAt" DATETIME NOT NULL,
    "__v" INTEGER NOT NULL DEFAULT 0
);

-- CreateTable
CREATE TABLE "medici_balances" (
    "_id" TEXT NOT NULL PRIMARY KEY,
    "key" TEXT NOT NULL,
    "rawKey" TEXT NOT NULL,
    "book" TEXT NOT NULL,
    "account" TEXT,
    "transaction" TEXT NOT NULL,
    "meta" TEXT NOT NULL,
    "balance" REAL NOT NULL,
    "notes" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL,
    "expireAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "medici_id_sequence" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "seconds" INTEGER NOT NULL,
    "counter" INTEGER NOT NULL DEFAULT 0,
    "instance" BLOB NOT NULL
);

-- CreateIndex
CREATE INDEX "medici_transactions__journal_idx" ON "medici_transactions"("_journal");

-- CreateIndex
CREATE INDEX "medici_transactions_book_accounts_datetime_idx" ON "medici_transactions"("book", "accounts", "datetime");

-- CreateIndex
CREATE INDEX "medici_transactions_book_account_path_0_account_path_1_account_path_2_datetime_idx" ON "medici_transactions"("book", "account_path_0", "account_path_1", "account_path_2", "datetime");

-- CreateIndex
CREATE UNIQUE INDEX "medici_locks_account_book_key" ON "medici_locks"("account", "book");

-- CreateIndex
CREATE INDEX "medici_balances_key_idx" ON "medici_balances"("key");`;

/** Split the DDL into executable statements (the diff output ends each on ";\n"). */
export function splitStatements(ddl: string = DDL): string[] {
  return ddl
    .split(";")
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0);
}

/**
 * Create the schema (all tables + indexes) and seed the single-row
 * medici_id_sequence (ITD-89 amendment A): seconds/counter start at 0 and
 * the 5-byte instance is fixed at database creation.
 */
export async function createSchema(prisma: PrismaClient = getPrismaClient()): Promise<void> {
  await connectPrisma();
  for (const statement of splitStatements()) {
    await prisma.$executeRawUnsafe(statement);
  }
  await prisma.$executeRawUnsafe(
    "INSERT INTO medici_id_sequence (id, seconds, counter, instance) VALUES (1, 0, 0, ?)",
    crypto.randomBytes(5)
  );
}

/**
 * Drop everything and recreate the schema from the embedded DDL. This is
 * the reset path the test harness calls in a before() hook; it also works
 * on in-memory databases (where the DROPs are no-ops and every connection
 * starts empty).
 */
export async function resetDatabase(prisma: PrismaClient = getPrismaClient()): Promise<void> {
  await connectPrisma();
  for (const table of TABLES) {
    await prisma.$executeRawUnsafe(`DROP TABLE IF EXISTS ${table}`);
  }
  await createSchema(prisma);
}
